version: "3.9"

services: 
    postgres:
        image: postgres:latest
        env_file: 
            - .env
        ports: 
            - 5432:5432
        tty: true

    server:
        build: ./server
        env_file:
            - .env
        depends_on: 
            - postgres
        tty: true

    nginx:
        build: ./nginx
        ports:
            - 8080:8080
        depends_on: 
            - server
