version: "3.9"

services: 
    db:
        image: postgres:latest
        env_file: 
            - conn_pg.env
        ports: 
            - 5432:5432
    server:
        build: .
        env_file:
            - conn_pg.env
    nginx:
        image: nginx:latest
        ports:
            - 8000:8000
