version: "3.9"

services:
    postgres:
        image: postgres:latest
        env_file:
            - .env
        ports:
            - 5432:5432
        tty: true

    server:
        build: ./server
        env_file:
            - .env
        environment:
            - ENDPOINT_TO_PROFILE=/orders/assign
            - CPROFILE_DEST=/app/logs/cprofile.log
            - CPROFILE_SORT_BY=cumtime
            - CPROFILE_OUTPUT_NUMBER=50
            - TMALLOC_ENDPOINT=/orders/assign
            - TMALLOC_FILTER_PATTERN=/app/YandexSweets/*.py
        depends_on:
            - postgres
        tty: true
        volumes:
            - ./server/logs:/app/logs

    nginx:
        build: ./nginx
        ports:
            - 8080:8080
        depends_on:
            - server
