# Generated by Django 3.2.5 on 2021-07-22 20:59

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('courier_id', models.IntegerField(primary_key=True, serialize=False)),
                ('courier_type', models.CharField(choices=[('foot', 'foot'), ('bike', 'bike'), ('car', 'car')], default='foot', max_length=4)),
                ('regions', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('working_hours', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=12), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPack',
            fields=[
                ('pack_id', models.AutoField(primary_key=True, serialize=False)),
                ('assign_time', models.DateTimeField()),
                ('delivery_type', models.CharField(choices=[('foot', 'foot'), ('bike', 'bike'), ('car', 'car')], default='foot', max_length=4)),
                ('delivery_ended', models.BooleanField(default=False)),
                ('last_complete_time', models.DateTimeField()),
                ('total_weight', models.FloatField(default=0)),
                ('courier', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='YandexSweets.courier')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('weight', models.FloatField()),
                ('region', models.IntegerField()),
                ('delivery_hours', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=12), size=None)),
                ('delivery_time', models.IntegerField(blank=True, default=None, null=True)),
                ('delivery_pack', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='YandexSweets.deliverypack')),
            ],
        ),
    ]
